### ISSUE TITLE
failed to parse droidcam

### ISSUE THREAD

**Issue by JAicewizard** [Sighery/rustympkglib#2]
Droidcam is a package with multiple pkgname's, and this (and most other packages) assume it can only be one.
It would be very kind of you to support parsing packages with multiple names and have an easy way of getting the multiple names.

:)

**Comment by Sighery** [comment]
As of v0.1.1 it should be possible to parse `pkgname`s with multiple values. I've also added `pkgbase` parsing. There's also [a test](https://github.com/Sighery/rustympkglib/blob/5e030af9c4d945cefdf22452fe3bb6bc50a458fe/src/pkgdata.rs#L889-L1036) using the [droidcam `PKGBUILD` at the latest commit at time of writing](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=droidcam&id=a38db4187bbb01b949da451c17d224816de91493) and all seems to be working as expected.
